apiVersion: v1
kind: Service
metadata:
  name: skill-nest-frontend-service
  namespace: skill-nest
spec:
  selector:
    app: skill-nest-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
